# Generated by Django 4.2.1 on 2023-05-07 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="weather_type",
            field=models.CharField(
                choices=[
                    ("sunny", "Sunny"),
                    ("cloudy", "Cloudy"),
                    ("windy", "Windy"),
                    ("rainy", "Rainy"),
                    ("stormy", "Stormy"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="report",
            name="temperature",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(60.0),
                ]
            ),
        ),
    ]
