# Generated by Django 4.2 on 2023-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gif",
            name="categories",
            field=models.ManyToManyField(
                related_name="gif_categories", to="gifs.category"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="gifs",
            field=models.ManyToManyField(
                blank=True, related_name="category_gifs", to="gifs.gif"
            ),
        ),
    ]
