# Generated by Django 4.2 on 2023-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifs", "0003_remove_gif_categories_alter_category_gifs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
