# Generated by Django 4.2 on 2023-04-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gifs", "0004_aaa"),
    ]

    operations = [
        migrations.DeleteModel(name="Aaa",),
    ]
